---
namespace: herve4m
name: quay
version: 1.2.0
readme: README.md
authors:
  - Hervé Quatremain <rv4m@yahoo.co.uk>
description: Ansible modules to manage Quay Container Registry installations
license:
  - GPL-3.0-or-later
tags:
  - application
  - quay
  - registry
repository: https://github.com/herve4m/quay-collection

# The URL to any online docs
documentation: https://github.com/herve4m/quay-collection

# The URL to the home page of the collection/project
homepage: https://github.com/herve4m/quay-collection

# The URL to the collection issue tracker
issues: https://github.com/herve4m/quay-collection/issues
