---
name: Sanity Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: ansible_collections/herve4m/quay

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install required packages
        run: pip install -Iv ansible

      - name: Run sanity tests
        run: >
          ANSIBLE_TEST_PREFER_PODMAN=1 ansible-test sanity
          --docker default -v --color
        working-directory: ./ansible_collections/herve4m/quay
...
