---
name: Sanity Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible_collections/herve4m/quay

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install required packages
        run: pip install -Iv ansible

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
        working-directory: ./ansible_collections/herve4m/quay
...
