---
name: Sanity Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      # Work around https://github.com/actions/runner-images/issues/9425
      - uses: actions/checkout@v4
      - name: Install crun
        uses: ./.github/actions/fix-crun
        with:
          checksums: CHECKSUMS

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install required packages
        run: pip install -Iv ansible

      - uses: actions/checkout@v4
        with:
          path: ansible_collections/herve4m/quay

      - name: Run sanity tests
        run: >
          ANSIBLE_TEST_PREFER_PODMAN=1 ansible-test sanity
          --docker default -v --color
        working-directory: ./ansible_collections/herve4m/quay
...
