---
name: Linting Collection Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  documentation-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install required packages
        run: pip install -Iv ansible-core antsibull-docs

      - uses: actions/checkout@v4

      - name: Lint documentation
        run: antsibull-docs lint-collection-docs --plugin-docs .
...
