---
# This workflow action runs pre-commit, which executes Ansible and yaml linting
# See .pre-commit-config.yaml for more details
name: Code Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install required packages
        run: pip install -Iv ansible-core ansible-lint flake8 yamllint black

      - uses: pre-commit/action@v2.0.3
...
