---
- name: Ensure the user accounts exist
  herve4m.quay.quay_user:
    username: "{{ item['username'] }}"
    email: "{{ item['email'] | default(omit) }}"
    password: "{{ item['password'] | default(omit) }}"
    state: present
    quay_token: "{{ quay_token | default(omit) }}"
    quay_username: "{{ quay_username | default(omit) }}"
    quay_password: "{{ quay_password | default(omit) }}"
    quay_host: "{{ quay_host | default(omit) }}"
    validate_certs: "{{ quay_validate_certs | default(omit) }}"
  loop: "{{ quay_org_users }}"
...
